name: twitter
author: sh4869 <nobuk4869@gmail.com> # name <email>
homepage: https://github.com/sh4869/twitter.dart # https://github.com/user/repo
version: 1.0.0
environment:
  sdk: ">=2.10.0 <3.0.0"
description: Twitter API Library
publish_to: none
dependencies:
  oauth:
    git:
      url: https://github.com/dukefirehawk/oauth.dart.git
      ref: sdk-2.12.x
  http: ^0.13.0
dev_dependencies:
  test: ^1.16.5
